name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5
    - name: Install dependencies
      run: |
        opam install tls
        opam install . --deps-only --with-doc --with-test
    - name: Build
      run: opam exec -- dune build
    - name: Test
      run: opam exec -- dune runtest
    - name: Build documentation
      run: opam exec -- dune build @doc
    - name: Upload website artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: _build/default/_doc/_html
  # deploy:
    # needs: build
    # permissions:
      # pages: write
      # id-token: write
    # environment:
      # name: github-pages
      # url: ${{ steps.deployment.outputs.page_url }}
    # runs-on: ubuntu-latest
    # steps:
      # - name: Deploy website
        # id: deployment
        # uses: actions/deploy-pages@v2
