name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get -y install ocaml ocaml-dune ocaml-odoc
    - name: Build
      run: dune build
    - name: Test
      run: dune runtest
    - name: Build documentation
      run: dune build @doc
    - name: Upload website artifact
      uses: actions/upload-artifact@v4
      with:
        path: _build/default/_doc/_html
        name: github-pages
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v2
